### ISSUE TITLE
Feature parity

### ISSUE THREAD

**Issue by yuchi** [yuchi/TiShimmer#1]
We’ll need to merge the APIs, and the package. Once I finish the Android version we’ll merge them.

What do you think @boardmain? :)

**Comment by boardmain** [comment]
ok

**Comment by yuchi** [comment]
**EN** By now the iOS version just creates a TextView. Could it be modified to create a ShimmerView so that it can be used as a container for arbitrary views? By now that’s exactly what I’m doing on Android.

**IT** In questo momento la version per iOS può creare solo delle TextView. Sarebbe possibile modificarla in modo che crei una ShimmerView che faccia da container per tutti i tipi di vista? È quello che ora fa la versione Android.

**Comment by yuchi** [comment]
Closing for obsolescence
