### ISSUE TITLE
Ensure ARC for FBShimmering*

### ISSUE THREAD

**Issue by yuchi** [yuchi/TiShimmer#2]
The original iOS Shimmer requires ARC. We need to make it work politely with Titanium. Probably the `-fobjc-arc` flag could do the job.

Pinging @omorandi for this: can you give us a few hints?

**Comment by omorandi** [comment]
Yes, iOS Ti modules are non-ARC, so you must add that flag for every ARC .m file you use in the target > build phases > compile sources settings.

**Comment by yuchi** [comment]
Great!

**Comment by yuchi** [comment]
How does [this issue](https://jira.appcelerator.org/browse/TIMOB-12558) relates to this case? Do we need to raise the minsdk to 3.1?

**Comment by omorandi** [comment]
Isn't the min-sdk already set to 3.2.0.GA?

**Comment by yuchi** [comment]
Yes it is… silly me.
