### ISSUE TITLE
Speed setting doesn't seem to be working

### ISSUE THREAD

**Issue by hijohnnylin** [yuchi/TiShimmer#3]
Hey! Fantastic work!! .speed parameter doesn't seem to be working for me though - perhaps I'm doing it wrong?

var Shimmer = require("it.ti.shimmer");

var v = Shimmer.createShimmeringView({
    top:170,
    width:Ti.UI.SIZE,
    height:Ti.UI.SIZE,
    backgroundColor: "transparent"
});
var z = Ti.UI.createLabel({
    text:'Loading...',
    textAlign:Ti.UI.TEXT_ALIGNMENT_CENTER,
    color:'#8671b3',
    font: {
        fontSize:36,
        fontFamily:'HelveticaNeue-Thin'
    }
});
v.add(z); 
v.startShimmering();
$.someView.add(v);

v.speed = 10; // doesn’t seem to be working, even after window is open

**Comment by yuchi** [comment]
The API is not standardized yet, and by now all the properties are accessible through `shimmering*` keys. In your case it's `shimmeringSpeed` :)

**Comment by hijohnnylin** [comment]
Perfect. Thank you!
