### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kopiro** [yuchi/TiShimmer#5]
Please update your README with a full example of how this module works.

``` javascript
var $shimWin = Ti.UI.createWindow({ modal: true});
var shimmeringView = require('it.ti.shimmer').createShimmeringView({ /* ... */ });

var label = Ti.UI.createLabel({ text: 'Hallo yozef' });
shimmeringView.add(label);
$shimWin.add(shimmeringView);

$shimWin.open();
shimmeringView.startShimmering();
```

This, doesn't work.

**Comment by yuchi** [comment]
A lot of things to not work on this module! :)

On #4 I give a small info about how to make it work.

Actually are you interested to help me and @boardmain in developing the feature parity? (This is an **Italian** community project, after all :D )

**Comment by kopiro** [comment]
Yes, certainly!

**Comment by yuchi** [comment]
Reviewing your issues with the GitHub app? :)
